### ISSUE TITLE
Invalid code generated by SWIG 1.3

### ISSUE THREAD

**Issue by Dapid** [ezralanglois/arachnid#3]
The code generated by SWIG is incorrect. Installing raises an error:

    arachnid/core/learn/core/fastdot_wrap.cpp:870:42: error: format not a string literal and no format arguments [-Werror=format-security]
    
         PyErr_Format(PyExc_RuntimeError, mesg);
    
                                              ^
SWIG 3.0.2 generates correct code. It can manually fixed to 

         PyErr_Format(PyExc_RuntimeError, "%s", mesg);

in three places, but that shouldn't be done.

**Comment by ezralanglois** [comment]
I checked in your pull request. Thanks!
